USE [master]
GO

/****** Object:  Database [demobd]    Script Date: 10.12.2021 17:44:54 ******/
CREATE DATABASE [demobd]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'demobd', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\demobd.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'demobd_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\demobd_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [demobd].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [demobd] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [demobd] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [demobd] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [demobd] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [demobd] SET ARITHABORT OFF 
GO

ALTER DATABASE [demobd] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [demobd] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [demobd] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [demobd] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [demobd] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [demobd] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [demobd] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [demobd] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [demobd] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [demobd] SET  DISABLE_BROKER 
GO

ALTER DATABASE [demobd] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [demobd] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [demobd] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [demobd] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [demobd] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [demobd] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [demobd] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [demobd] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [demobd] SET  MULTI_USER 
GO

ALTER DATABASE [demobd] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [demobd] SET DB_CHAINING OFF 
GO

ALTER DATABASE [demobd] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [demobd] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [demobd] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [demobd] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [demobd] SET QUERY_STORE = OFF
GO

ALTER DATABASE [demobd] SET  READ_WRITE 
GO


